### ISSUE TITLE
Implement Dark mode in the application

### ISSUE THREAD

**Issue by amanjagdev** [radioactive11/HealthBridge#6]
Implement dark mode through a toggle switch in a dark mode which switched between light and dark mode
Dark mode settings must persist even after refreshing the page

PS: You can make use of the sass variables present

**Comment by kg-kartik** [comment]
@amanjagdev I would like to work on this issue!

**Comment by Ayush-Khandelwal-007** [comment]
Please assign me. I would like to help.

**Comment by amanjagdev** [comment]
@Ayush-Khandelwal-007  You can start working on this :)

**Comment by Ayush-Khandelwal-007** [comment]
Sir , could you please add label for **hactoberfest** **topic** to your repo. It would be helpful to me.

**Comment by radioactive11** [comment]
Topic added

**Comment by Ayush-Khandelwal-007** [comment]
Please ignore the closed PR , i left out few things and created some errors which are now fixed and app is working properly.

**Comment by amanjagdev** [comment]
Solved by #8
